In [145]:
import pandas as pd
df=pd.read_csv('csv_result-caesarian.csv')
df.head()

id  'Age'  'Delivery  'Delivery.1  'Blood  'Heart  Caesarian
0   1     22          1            0       2       0          0
1   2     26          2            0       1       0          1
2   3     26          2            1       1       0          0
3   4     28          1            0       2       0          0
4   5     22          2            0       1       0          1

In [146]:
df.describe()

id      'Age'  'Delivery  'Delivery.1     'Blood     'Heart  \
count  80.0000  80.000000  80.000000    80.000000  80.000000  80.000000   
mean   40.5000  27.687500   1.662500     0.637500   1.000000   0.375000   
std    23.2379   5.017927   0.794662     0.815107   0.711568   0.487177   
min     1.0000  17.000000   1.000000     0.000000   0.000000   0.000000   
25%    20.7500  25.000000   1.000000     0.000000   0.750000   0.000000   
50%    40.5000  27.000000   1.000000     0.000000   1.000000   0.000000   
75%    60.2500  32.000000   2.000000     1.000000   1.250000   1.000000   
max    80.0000  40.000000   4.000000     2.000000   2.000000   1.000000   

       Caesarian  
count  80.000000  
mean    0.575000  
std     0.497462  
min     0.000000  
25%     0.000000  
50%     1.000000  
75%     1.000000  
max     1.000000

# data preprocessing

In [147]:
import numpy as np
Xc=df.columns[0:]
X=df[Xc[1:6]].values
Y=df[Xc[6]].values
Y=Y.reshape(80,1)
print(X.shape)
print(Y.shape)
print(X[0:4])

(80, 5)
(80, 1)
[[22  1  0  2  0]
 [26  2  0  1  0]
 [26  2  1  1  0]
 [28  1  0  2  0]]


In [148]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.1,random_state=0)

# Perceptron

In [152]:
import numpy as np

class Perceptron(object):
    def __init__(self,eta=0.01,n_iter=10):
        self.eta=eta
        self.n_iter=n_iter
    def fit(self,X,y):  #to train
        self.w_=np.zeros(1+X.shape[1])  # weights and bias shapereturns dimension as tuple
        for _ in range(self.n_iter):
            for xi, target in zip(X,y):  #zip used to unfold value in two arrays one by one
                error=target-self.predict(xi)
                if error!=0:
                    update = self.eta * (target-self.predict(xi))
                    self.w_[1:] += update * xi
                    self.w_[0] += update*1
        return self
    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.w_[1:]) + self.w_[0]
    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >=0.0, 1, 0)
ob=Perceptron(eta=0.01,n_iter=60)
ob.fit(X_train,y_train)
print(ob.w_)
res=ob.predict(X_test)
restrain=ob.predict(X_train)

[-0.26  0.09  1.01 -0.15 -0.94  3.34]


In [153]:
from sklearn.metrics import accuracy_score
print('Accuracy of training data:'+str(accuracy_score(y_train,restrain)*100))
print('Accuracy of testing data:'+str(accuracy_score(y_test,res)*100))

Accuracy of training data:56.94444444444444
Accuracy of testing data:62.5


# SVM

In [154]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [155]:
from sklearn.svm import SVC
svm = SVC(kernel='linear', C=100, random_state=0)
svm.fit(X_train, y_train)
y_predtrain=svm.predict(X_train)
y_predtest=svm.predict(X_test)

In [156]:
from sklearn.metrics import accuracy_score
print('Accuracy of training data:'+str(accuracy_score(y_train,y_predtrain)*100))
print('Accuracy of testing data:'+str(accuracy_score(y_test,y_predtest)*100))

Accuracy of training data:73.4375
Accuracy of testing data:75.0


# LVQ

In [173]:
import numpy as np
def LVQ(x,tar):
    W=np.zeros((2,x.shape[1]))
    lr=0.5
    d=[0,0]
    e=1
    while(e<=10):
      for i in range(x.shape[0]):
        for j in range(W.shape[0]):
          d[j]=np.sum((x[i,:]-W[j,:])**2)
          d[j]=d[j]**0.5
        if(d[0]<d[1]):
          t=0
          #print("winning neuron is ",0)
        else:
          t=1
          #print("winning neuron is", 1)
        if(t==tar[i]):
          W[t,:]+=lr*(x[i,:]-W[t,:])
        else:
           W[t,:]-=lr*(x[i,:]-W[t,:])
      print("Updated weights at epoch ",e,"are ",W)
      e+=1
      lr=0.5*lr
      
    return W

In [174]:
W=LVQ(X_train,y_train)

Updated weights at epoch  1 are  [[-8.86079673e+01 -7.67827761e+00  4.00379241e+00 -3.56223583e-01
  -6.83013582e+00]
 [ 3.41816080e+01  3.64330975e+00 -5.23903051e-02  1.56153710e+00
   6.14453898e-01]]
Updated weights at epoch  2 are  [[-88.60796726  -7.67827761   4.00379241  -0.35622358  -6.83013582]
 [ 34.48543569   3.5661211    0.21155177   1.2447972    1.01698491]]
Updated weights at epoch  3 are  [[-88.60796726  -7.67827761   4.00379241  -0.35622358  -6.83013582]
 [ 33.05183089   3.12434043   0.21762412   1.05558098   1.16090668]]
Updated weights at epoch  4 are  [[-88.60796726  -7.67827761   4.00379241  -0.35622358  -6.83013582]
 [ 32.16579867   2.89957248   0.18774867   0.96308113   1.18821946]]
Updated weights at epoch  5 are  [[-88.60796726  -7.67827761   4.00379241  -0.35622358  -6.83013582]
 [ 31.7455278    2.80156625   0.16813462   0.91752718   1.19999349]]
Updated weights at epoch  6 are  [[-88.60796726  -7.67827761   4.00379241  -0.35622358  -6.83013582]
 [ 31.54452195 

In [172]:
def LVQt(X,Y,W):
    d=[0,0]
    print(W)
    res=np.zeros(Y.shape)
    for i in range(X.shape[0]):
        for j in range(W.shape[0]):
            d[j]=np.sum((X[i,:]-W[j,:])**2)
            d[j]=d[j]**0.5
        if d[0]<d[1]:
            res[i]=0
        else:
            res[i]=1
    return res
y_predtrain=LVQt(X_train,y_train,W)
y_pred=LVQt(X_test,y_test,W)
from sklearn.metrics import accuracy_score
print('Accuracy:'+str(accuracy_score(y_train,y_predtrain)*100))
print('Accuracy:'+str(accuracy_score(y_test,y_pred)*100))

[[-88.60796726  -7.67827761   4.00379241  -0.35622358  -6.83013582]
 [ 31.36224753   2.71754208   0.14664877   0.8733852    1.21245103]]
[[-88.60796726  -7.67827761   4.00379241  -0.35622358  -6.83013582]
 [ 31.36224753   2.71754208   0.14664877   0.8733852    1.21245103]]
Accuracy:59.375
Accuracy:50.0


# SOM

In [167]:
import numpy as np
#x=np.array([[0,0,1,1],[1,1,0,0]])
def SOM(x,y):
    W=np.zeros((2,x.shape[1]))
    lr=1
    d=[0,0]
    e=1
    res=np.zeros(y.shape)
    while(e<=10):
      for i in range(x.shape[0]):
        for j in range(W.shape[0]):
          d[j]=np.sum((x[i,:]-W[j,:])**2)
          d[j]=d[j]**0.5
        print(d)
        if(d[0]<d[1]):
          t=0
          res[i]=0
          #print("winning neuron is ",0)
        else:
          t=1
          res[i]=1
          #print("winning neuron is", 1)
        W[t,:]+=lr*(x[i,:]-W[t,:])
      print("Updated weight at epoch ",e,"are ",W)
      e+=1
      lr=0.5*lr
    return W

In [168]:
trainedweights=SOM(X_train,y_train)

4379907536]
[25.03996805109783, 2.4451892853525954]
[21.142374511865974, 5.751421230299863]
[26.057628441590765, 1.142403586514523]
[38.23610858861032, 12.828118165118056]
[28.089143810376278, 1.3892531135996755]
[20.074859899884732, 8.519212086070786]
[18.05547008526779, 8.375406899624842]
[31.144823004794873, 6.968518165720404]
[26.038433132583073, 1.1032650449248864]
[26.115129714401192, 1.9181615681479423]
[35.07135583350036, 9.133125081495853]
[26.095976701399778, 2.6841008045641312]
[23.065125189341593, 4.707419506442139]
[17.029386365926403, 9.588629939330037]
[33.04542328371661, 8.89654822452985]
[33.075670817082454, 6.853650071827037]
[27.055498516937366, 1.2899783388761452]
[33.25657829663178, 5.950697492420811]
[29.103264421710495, 0.9573458797732114]
[31.160872901765764, 3.0330966067178]
[32.14031735997639, 2.7679555165883563]
[36.29049462324811, 6.317131915169289]
Updated weight at epoch  3 are  [[ 0.          0.          0.          0.          0.        ]
 [31.61472064  

In [169]:
import numpy as np
def SOMt(x,y,W):
    #W=np.array([[0.8,0.7,0.2,0.2,0.1],[0.1,0.2,0.3,0.4,0.1]])
    lr=0.5
    d=[0,0]
    e=1
    res=np.zeros(y.shape)
    for i in range(x.shape[0]):
        for j in range(W.shape[0]):
          d[j]=np.sum((x[i,:]-W[j,:])**2)
          d[j]=d[j]**0.5
        if(d[0]<d[1]):
          t=0
          res[i]=0
        else:
          t=1
          res[i]=1
    return res

In [170]:
y_predtrain=SOMt(X_train,y_train,trainedweights)
y_predtest=SOMt(X_test,y_test,trainedweights)

In [171]:
from sklearn.metrics import accuracy_score
print('Accuracy of training data:'+str(accuracy_score(y_train,y_predtrain)*100))
print('Accuracy of testing data:'+str(accuracy_score(y_test,y_predtest)*100))

Accuracy of training data:59.375
Accuracy of testing data:50.0
